# Generated by Django 3.0.5 on 2020-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='liters_of_milk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='production_time',
            field=models.DateTimeField(null=True),
        ),
    ]
