# Generated by Django 3.0.5 on 2020-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200517_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
