# Generated by Django 3.0.5 on 2020-05-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_driver_farmer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInput',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('save_option', models.CharField(blank=True, max_length=100, verbose_name='Save to')),
                ('_redirect', models.ForeignKey(blank=True, help_text='The element to redirect to after the key_input has been played.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_keyinput_related', to='service_development.VoiceServiceElement', verbose_name='Redirect element')),
            ],
            options={
                'verbose_name': 'Key input Element',
            },
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
