# Generated by Django 3.0.5 on 2020-05-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_auto_20200516_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyinput',
            name='_redirect_fail',
            field=models.ForeignKey(blank=True, help_text='The element to redirect to after a failed input', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_keyinput_related_fail', to='service_development.VoiceServiceElement', verbose_name='Redirect fail element'),
        ),
    ]
